Reorganized sample directory
ndtp/android-testify pull request #121
Opened 2023-04-28 18:58 UTC by andrew-carmichael

### What does this change accomplish?
Created a 'Samples' directory and renamed the existing sample to 'LegacySample'

Resolves <issues>

### How have you achieved it?
Simply renamed the directories and patched up the grade files so things build correctly.

### Tophat instructions
...

### Notice

This change must keep `main` in a shippable state; **it may be shipped without further notice**.

2023-04-28 20:17 UTC, DanielJette commented
We need to update the documentation:

```
./RECIPES.md:48:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/main/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/main/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./Plugins/Gradle/README.md:150:  baselineSourceDir    = /Users/ndtp/android-testify/Sample/src/androidTest/assets/screenshots
./Ext/Fullscreen/README.md:50:Additonal examples can be found in [FullscreenCaptureExampleTest.kt](../../Sample/src/androidTest/java/dev/testify/sample/FullscreenCaptureExampleTests.kt).
./docs/docs/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./docs/versioned_docs/version-2.0.0-alpha01/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./docs/versioned_docs/version-1.2.0-alpha01/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/6a04294efc63f736654760288892880ee2a1d1c8/Library/src/main/java/com/shopify/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/6a04294efc63f736654760288892880ee2a1d1c8/Sample/src/androidTest/java/com/shopify/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
```

2023-05-01 00:58 UTC, DanielJette requested changes
We need to update the documentation:

```
./RECIPES.md:48:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/main/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/main/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./Plugins/Gradle/README.md:150:  baselineSourceDir    = /Users/ndtp/android-testify/Sample/src/androidTest/assets/screenshots
./Ext/Fullscreen/README.md:50:Additonal examples can be found in [FullscreenCaptureExampleTest.kt](../../Sample/src/androidTest/java/dev/testify/sample/FullscreenCaptureExampleTests.kt).
./docs/docs/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./docs/versioned_docs/version-2.0.0-alpha01/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Library/src/main/java/dev/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/230607acc598afe7d54f9618d55fdecd0da83800/Sample/src/androidTest/java/dev/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
./docs/versioned_docs/version-1.2.0-alpha01/recipes/2-locale.md:7:To begin, if you are targeting an emulator running Android API 24 or higher, your activity under test must implement the [TestifyResourcesOverride](https://github.com/ndtp/android-testify/blob/6a04294efc63f736654760288892880ee2a1d1c8/Library/src/main/java/com/shopify/testify/resources/TestifyResourcesOverride.kt) interface. This allows Testify to attach a new `Context` with the appropriate locale loaded. It is highly recommended that you employ a _test harness activity_ for this purpose. Please see the [TestHarnessActivity](https://github.com/ndtp/android-testify/blob/6a04294efc63f736654760288892880ee2a1d1c8/Sample/src/androidTest/java/com/shopify/testify/sample/test/TestLocaleHarnessActivity.kt) in the provided Sample.
```

2023-05-02 22:11 UTC, DanielJette approved these changes

2023-05-02 22:11 UTC, merged

2023-05-03 01:12 UTC, andrew-carmichael commented
:partying_face: